var rule = {
  title: '火狐影视',
  host: 'https://www.ketv.cc/',
  url: '/s/fyclass--------fypage---.html',
//https://www.ketv.cc/s/fyclass--------fypage---.html
  searchUrl: '/vod-search-page-fypage-wd-**.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  class_parse: '.top_nav.clearfix li;a&&Text;a&&href;/.*-(.*?).html',
  play_parse: true,
  lazy: '',
  limit: 6,
  推荐: '.cbox_list li;.vodlist_item;a&&title;.lazyload&&data-original;.pic_text&&Text;a&&href',
  double: true,
  一级: '.vodlist_item;a&&title;.lazyload&&data-original;.pic_text&&Text;a&&href',
  二级: {
    title: '.hd_tit.fl&&Text',
    img: '.lazyload&&data-original',
    desc: '.text_muted hidden_xs:eq(0)&&Text;.text_muted hidden_xs:eq(1)&&Text;.text_muted hidden_xs:eq(2)&&Text;.text_muted hidden_xs:eq(3)&&Text',
    content: '.left.text_muted&&Text',
    tabs: '#NumTab&&a',
    lists: '.play_list_box:eq(#id)&&.playlist_notfull&&a',
  },
  搜索: '.vodlist_item;a&&title;.lazyload&&data-original;.pic_text&&Text;a&&href',
}
