var rule = {
  title: '稀饭动漫',
  host: 'https://dm.xifanacg.com',
  class_name: '连载新番&完结旧番&剧场版&美漫',
  class_url: '1&2&3&21',
  searchUrl: '/search.html?wd=**',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/index.php/ds_api/vod#type=fyclass&page=fypage',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/bangumi/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let playerMatch = html.match(/var player_aaaa\\s*=\\s*(\\{.*?\\})\\s*;/);\n  if (playerMatch) {\n    try {\n      let json = JSON5.parse(playerMatch[1]);\n      let url = json.url;\n      if (json.encrypt == '1') {\n        url = unescape(url);\n      } else if (json.encrypt == '2') {\n        url = unescape(base64Decode(url));\n      }\n      if (/(\\.m3u8|\\.mp4)/i.test(url)) {\n        input = {parse:0, jx:0, url: url};\n      } else {\n        input = {parse:0, jx:1, url: url};\n      }\n    } catch (e) {\n      console.error('解析失败:', e);\n      let iframeSrc = html.match(/<iframe[^>]+src=['\"]([^'\"?#]+)/i)?.[1];\n      if (iframeSrc) {\n        let urlParam = new URLSearchParams(iframeSrc.split('?')[1]).get('url');\n        if (urlParam) {\n          input = {parse:0, jx:0, url: decodeURIComponent(urlParam)};\n        }\n      }\n    }\n  }",
  limit: 6,
  推荐: '.list-swiper .public-list-box;a&&title;.lazy&&data-src;.public-list-prb&&Text;a&&href',
  一级: 'js:let body=input.split("#")[1];let t=Math.round(new Date/1e3).toString();let key=md5("DS"+t+"DCC147D11943AF75");let url=input.split("#")[0];body=body+"&time="+t+"&key="+key;print(body);fetch_params.body=body;let html=post(url,fetch_params);let data=JSON.parse(html);VODS=data.list.map(function(it){it.vod_pic=urljoin2(input.split("/i")[0],it.vod_pic);return it});',
  二级: {
    title: '.slide-info-title&&Text;.slide-info:eq(2)--strong&&Text',
    img: '.detail-pic&&data-original',
    desc: '.slide-info-remarks&&Text;.slide-info-remarks:eq(1)&&Text;.slide-info-remarks:eq(2)&&Text;.slide-info:eq(1)--strong&&Text;.info-parameter&&ul&&li:eq(3)&&Text',
    content: '#height_limit&&Text',
    tabs: '.anthology.wow.fadeInUp.animated&&.swiper-wrapper&&a',
    tab_text: 'a--span&&Text',
    lists: '.anthology-list-box:eq(#id) li',
  },
  搜索: '.row .vod-detail;.slide-info-title&&Text;.lazy&&data-src;.slide-info&&Text;a&&href',
}
